### ISSUE TITLE
Build caching is disabled

### ISSUE THREAD

**Issue by McSinyx** [WolfireGames/overgrowth#12]
Most (if not all) generated make targets are marked as .PHONY, and thus objects are never cached.  This make incremental development (or just trying to get it compile correctly for the first time) rather painful.  Unfortunately I do no know CMake well enough to suggest where to look at to toggle caching back.

In case it just happens to me, I am on NixOS unstable and trying to build the engine in the following shell:

```nix
with import <nixpkgs> {};
mkShell {
  nativeBuildInputs = [ cmake pkg-config ];
  buildInputs = [
    libGL libGLU SDL2 SDL2_net gtk2 glib
    openal libogg libvorbis libtheora
    libjpeg freeimage freetype bzip2
  ];

  shellHook = ''
    cmake -S ./Projects -B ./Build\
      -DGTK2_GDKCONFIG_INCLUDE_DIR=${gtk2.out}/lib/gtk-2.0/include\
      -DGTK2_GLIBCONFIG_INCLUDE_DIR=${glib.out}/lib/glib-2.0/include
  '';
}
```

**Comment by autious** [comment]
I don't believe our CMakeLists file is explicitally disabling any caching on purpose, but it's possible it's doing so incidentally.

**Comment by Conan-Kudo** [comment]
CMake doesn't use the Makefile caching mechanism for incremental caching. The Makefiles call back into CMake for determining what to build, so already built targets will get skipped correctly. That's why Makefiles are PHONY targets.

Same goes for Ninja or any other target CMake generates.

**Comment by shinymerlyn** [comment]
Does that mean this issue should be closed?

**Comment by McSinyx** [comment]
I think so.
