### ISSUE TITLE
Can't connect pathpoints to each other or characters anymore.

### ISSUE THREAD

**Issue by Gyrth** [WolfireGames/overgrowth#120]
To make AI walk around the level OG uses pathpoint objects. These objects can be placed and moved in the level to lay out a path for characters. The connecting no longer works in the FOSS version of the engine. 

Using 1500b7bd19ae685e84423648ddf4404bcdfda7ff
With ``Alt + LMB`` with a pathpoint selected you should be able to connect it to a character or another pathpoint. But this no longer works.

![image](https://github.com/WolfireGames/overgrowth/assets/14081613/69034f62-bf42-4d75-986f-0ea4a8c94f22)

**Comment by kavika13** [comment]
Should be fixed by 0256b3f30badd87a9450c329bd84d78fcf45394e
