### ISSUE TITLE
This item [in Steam] is currently unavailable in your region

### ISSUE THREAD

**Issue by xDShot** [WolfireGames/overgrowth#17]
How am I suppose to work with code if it required to
>have installed a commercial version of the game  

when you do not allow purchasing in banned regions. Looks so ridiculous with such dirty politics...

**Comment by autious** [comment]
As far as i know, Wolfire Games is not actively banning the sale in any region, unless forced to do so by law.

**Comment by xDShot** [comment]
Proof
![image](https://user-images.githubusercontent.com/4261659/164784248-e83e6641-1cbf-4eb8-bd38-cda31ad074f4.png)

**Comment by xDShot** [comment]
>forced to do so by law.
'd like to see what law it enforces to block purchase. I assume Wolfire Games is company from US, then why not all companies block purchases then.

**Comment by McSinyx** [comment]
Is Humble Bundle not selling non-Steam Overgrowth anymore?
I got my non-DRM copy not so long ago.

**Comment by autious** [comment]
I'm looking into the sales restrictions on Steam, trying to figure it out.

And yes, the game is available on Humble Bundle and Itch.io

**Comment by lukors** [comment]
Unfortunately, we can't do much about this. David wrote this in Discord:

> If Steam is currently allowing their economy to be used to trade rubles for digital items like games that can later be traded for USD or Euros (even on external sites), that sounds like it could violate a ton of new trade and finance laws. There is no user interface for developers to block regions; that is all handled manually by Valve employees, so to make sure my store page is working in Russia I would have to email them about it and basically ask them in writing to commit a crime.

Link to first of three messages: https://discord.com/channels/223363757898858496/231496507679834122/960310145253003356

I'm closing this since it's out of our hands. Hopefully, this situation will be resolved soon.
