### ISSUE TITLE
Problem with cmake

### ISSUE THREAD

**Issue by GunpowderGuy** [WolfireGames/overgrowth#74]
When i follow the steps in compiling.rmd, i get the following error:

CMake Error at /home/username/Documents/overgrowth /Libraries/freetype-2.12.1/CMakeLists.txt:222 (message):
  In-source builds are not permitted! Make a separate folder for building,
  e.g.,

    cmake -E make_directory build
    cmake -E chdir build cmake ..

  Before that, remove the files created by this failed run with

    cmake -E remove CMakeCache.txt
    cmake -E remove_directory CMakeFiles

**Comment by shinymerlyn** [comment]
This error message to me looks like you might not be following all the instructions here:
https://github.com/WolfireGames/overgrowth/blob/main/COMPILING.md

Need to make a `<git root>/build` dir, cd into it, and run `cmake ../Projects <other flags here>`.

The error message makes me think cmake may have been invoked either from the git root, or the Projects folder?
