### ISSUE TITLE
Game crashes on Windows when I load any level

### ISSUE THREAD

**Issue by diegomacario** [WolfireGames/overgrowth#79]
Hi maintainers! Today I bought a copy of overgrowth because I'm very interested in studying this codebase.

I used CMake to create a Visual Studio 2022 solution, and I built the game successfully. I can launch the game, but when I choose any level it immediately crashes. This is what I see in Visual Studio:

<img width="594" alt="Exception" src="https://user-images.githubusercontent.com/8304271/188691585-4bd4b1e1-c7cf-41f7-a345-aff06fee39bb.PNG">

Have you ever seen this before?

I installed Overgrowth here through steam: C:\Program Files (x86)\Steam\steamapps\common\Overgrowth

And I built it here: C:\overgrowth\Build

Please let me know if there's any additional information that I can provide. Thank you!

**Comment by McSinyx** [comment]
While it could be an actual bug (out of bound array access)
that is optimized away in release build, could you please check
if it is caused by engine-data mismatch (GH-18)?

**Comment by diegomacario** [comment]
@McSinyx I'm actually already using the `internal_testing` branch, but I just discovered something: I launched the game through steam, and it crashed doing the same thing (loading levels). So it really looks like the `internal_testing` branch is currently broken. It would be great if one of the maintainers could confirm that.

**Comment by diegomacario** [comment]
@feliwir I'm starting to believe that this crash might be related to your replacement of `FreeImage` with `stb` (https://github.com/WolfireGames/overgrowth/pull/58).

I deleted the Wolfire folder that contains cached data, launched the game, and it crashes here:

<img width="923" alt="Free_Image" src="https://user-images.githubusercontent.com/8304271/188886271-b3088593-1d09-4917-82a9-86ea82a207c7.PNG">

While loading some textures:

<img width="871" alt="Tex" src="https://user-images.githubusercontent.com/8304271/188886318-b8079129-d14b-44a1-beab-1822a0a77929.PNG">

Could you try to reproduce the crash on your side? Thank you!

**Comment by diegomacario** [comment]
@feliwir @Conan-Kudo @akien-mga @autious I created this PR to fix the crashes I described above: https://github.com/WolfireGames/overgrowth/pull/80

Now I'm able to launch some sandbox levels successfully, but this bug still prevents me from loading the story levels: https://github.com/WolfireGames/overgrowth/issues/78

Please take a look at my PR and if possible at the bug I mentioned above. This repo is so useful, it's a shame it's currently broken like this.

**Comment by diegomacario** [comment]
This issue was fixed in this PR: https://github.com/WolfireGames/overgrowth/pull/83

So I will close it now.
