### ISSUE TITLE
Mistake in build instructions?

### ISSUE THREAD

**Issue by taoeffect** [WolfireGames/overgrowth#81]
In the macOS and Linux sections of [COMPILING.md](https://github.com/WolfireGames/overgrowth/blob/main/COMPILING.md) it says:

> Go to the folder of the project

And: 

> cmake ../Projects -DAUX_DATA="/path/to/installed/Overgrowth.app/Contents/MacOS"

One of these has to be wrong, because in the root directory the Projects folder is `./Projects`, not `../Projects`. So either there's a missing folder you're supposed to go into originally, or the instructions mean you're supposed to `cd Build` but don't say that, or `..` should be `.`. Which is it?

**Comment by McSinyx** [comment]
Yea step 2 should include changing
into the newly created build directory.
