### ISSUE TITLE
Engine Error - Error opening zipfile

### ISSUE THREAD

**Issue by ipro4911** [WolfireGames/overgrowth#82]
With Navmesh i cant get into game cuz it cant save/open a file nav for maps any idk if its just 1 file but always get this error,i try to switch to normal version but i think navmesh.cpp is outdaded or smth? just my guess

**Comment by shinymerlyn** [comment]
Duplicate of #78 

This is a known issue, and Max told me he'll look into it soon. It is due to how libfreetype uses zlib. Upgrading that library caused a ripple effect and broke minizip, which is what the engine uses to open these navmesh zip files.
