### ISSUE TITLE
How do I switch to internal_testing branch in steam?

### ISSUE THREAD

**Issue by haolly** [WolfireGames/overgrowth#86]
The COMPILING.md says `If you're on steam, you'll also want to make sure you're using the internal_testing branch to have the latest set of data-files for the game`, but how do I switch to internal_testing branch in steam?

**Comment by redruin1** [comment]
Its in the "Betas" tab if you right click on Overgrowth and select "Properties". This video released by Wolfire is comprehensive:
https://youtu.be/2d-fqRM8fa4?t=29
